version: "2"

services:
  web:
    container_name: web
    build:
        context: ./docker/nginx
        args:
          BUILD_ENV: PRODUCTION
    restart: always
    environment:
      NGINX_PORT: 8080
      NGINX_HOST: "localhost"
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./webapp:/var/www/html
    networks:
      - webapp-network
  php:
    container_name: php
    build: ./docker/php
    restart: always
    volumes:
      - ./webapp:/var/www/html
    networks:
      - webapp-network
  postgres:
    container_name: mysql
    environment:
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@$$W0rd}
      MYSQL_DATABASE: webapp
    build: ./docker/mysql
    restart: always
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - webapp-network

networks:
    webapp-network:
        driver: bridge
