#!/bin/bash

echo "Environment:" $APP_ENV "detected"

if [ "DEVELOPMENT" == "$APP_ENV" ]; then
    # Enable xdebug
    echo "Enabling XDEBUG"

    ## FPM
    ln -sf /etc/php/7.1/mods-available/xdebug.ini /usr/local/etc/php/conf.d/20-xdebug.ini

    ## CLI
    # ln -sf /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/cli/conf.d/20-xdebug.ini
else
    # Disable xdebug
    echo "Disabling XDEBUG"

    ## FPM
    if [ -e /usr/local/etc/php/conf.d/20-xdebug.ini ]; then
        rm -f /usr/local/etc/php/conf.d/20-xdebug.ini
    fi

    ## CLI
    if [ -e /etc/php/7.1/cli/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.1/cli/conf.d/20-xdebug.ini
    fi
fi

# Config /etc/php/7.1/mods-available/xdebug.ini
echo "XDEBUG_HOST is" $XDEBUG_HOST
sed -i "s/xdebug\.remote_host\=.*/xdebug\.remote_host\=$XDEBUG_HOST/g" /etc/php/7.1/mods-available/xdebug.ini
